### ISSUE TITLE
Create a StringConvert function

### ISSUE THREAD

**Issue by DevinJM3** [ACDC-KSU-Senior-Design/ACDC_SeniorProj#36]
Since part of the requirements for this project was to send debug information over a UART connection i think we should create some function (could be StringConvert) to convert a integer value to its corresponding string value 
```c
char *convertedNumber = StringConvert(123456); // Converts 123456 => "123456"
```  

or

```c
char *convertedNumber;
StringConvert(convertedNumber, 123456); // Converts 123456 => "123456"
```

**Comment by Sherwin-14** [comment]
Hey Devin, Can I take this issue up? If yes, do you have any specific opinions regarding this?

**Comment by DevinJM3** [comment]
fixed in a recent PR
